[versions]
agp = "8.0.1"
material = "1.6.1"
hilt = "2.46.1"
kotlin = "1.8.0"
ksp = "1.8.0-1.0.8"
retrofit = "2.9.0"
okHttp = "4.10.0"
moshi = "1.14.0"
glide = "4.13.2"
androidxActivity = "1.4.0"
androidxFragment = "1.5.1"
androidxLifecycle = "2.5.1"
androidxArchCore = "2.1.0"
androidxTest = "1.3.0"
androidxTestJunit = "1.1.2"
androidTestRunner = "1.3.0-beta01"
espresso = "3.3.0"
mockitoKotlin = "2.2.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-plugin = { id = "dagger.hilt.android.plugin", version = "hilt" }

[libraries]
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-arch-core = { module = "androidx.arch.core:core-testing", version.ref = "androidxArchCore" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
retrofit = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

